== Protection Profile for LiFi Access Systems

[cols="1,1,1,1,1,1,1,1"]
|===
8+|lifi-access-system
| https://github.com/commoncriteria/lifi-access-system/tree/main[main] 
a| https://commoncriteria.github.io/lifi-access-system/main/lifi-access-system-release.html[📄]
a|[link=https://github.com/commoncriteria/lifi-access-system/blob/gh-pages/main/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/lifi-access-system/gh-pages/main/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/lifi-access-system/blob/gh-pages/main/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/lifi-access-system/gh-pages/main/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/lifi-access-system/blob/gh-pages/main/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/lifi-access-system/gh-pages/main/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/lifi-access-system/blob/gh-pages/main/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/lifi-access-system/gh-pages/main/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/lifi-access-system/gh-pages/main/transforms.svg[transforms,150]
a| [link=https://github.com/commoncriteria/lifi-access-system/blob/gh-pages/main/HTMLs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/lifi-access-system/gh-pages/main/html_count.svg[HTML Count]
[link=https://github.com/commoncriteria/lifi-access-system/blob/gh-pages/main/PDFs.adoc]
image::https://raw.githubusercontent.com/commoncriteria/lifi-access-system/gh-pages/main/pdf_count.svg[PDF Count]
|===

=== Draft Version (latest build of main branch)
* https://commoncriteria.github.io/lifi-access-system/main/lifi-access-system-release-linkable.html[Protection
Profile for LiFi Access System] (html)
* https://commoncriteria.github.io/lifi-access-system/main/lifi-access-system-release-linkable.pdf[Protection
Profile for LiFi Access System] (pdf)

=== Release Version

* link:QQQQ[Protection Profile for QQQQ]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/lifi-access-system/issues[repository issue tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/lifi-access-system.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms
 git add transforms
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.
You shouldn’t need to modify it.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]

=== License

See link:./LICENSE[License]
